Repository Azure/azure-databricks-client, pull requests merged in 2024-11, with the labels that each got.

#230 Update and remove unused packages
  csharp/Microsoft.Azure.Databricks.Client.Sample/Microsoft.Azure.Databricks.Client.Sample.csproj
  csharp/Microsoft.Azure.Databricks.Client.Test/Microsoft.Azure.Databricks.Client.Test.csproj
  csharp/Microsoft.Azure.Databricks.Client/DatabricksClient.cs
  csharp/Microsoft.Azure.Databricks.Client/Microsoft.Azure.Databricks.Client.csproj
Labels: dependencies

#236 fix: MLFlow API GetRun type error
  csharp/Microsoft.Azure.Databricks.Client.Sample/SampleProgram.MachineLearning.cs
  csharp/Microsoft.Azure.Databricks.Client.Sample/SampleProgram.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/MachineLearning/ExperimentApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/MachineLearning/IExperimentApi.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/MachineLearning/Experiment/Run.cs
Labels: bug

#237 fix: PipelinesApiClient.ListPageable() throws when no pipelines are returned
  csharp/Microsoft.Azure.Databricks.Client/Models/PipelinesList.cs
Labels: bug

#238 fix: adding support for deserialization for StatementExecutionResultChunk.DataArray
  csharp/Microsoft.Azure.Databricks.Client.Test/StatementExecutionApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/StatementExecution.cs
Labels: enhancement, waiting for reply

#245 fix: use CPM to update vulnerable dependencies
  csharp/Directory.Packages.props
  csharp/Microsoft.Azure.Databricks.Client.Sample/Microsoft.Azure.Databricks.Client.Sample.csproj
  csharp/Microsoft.Azure.Databricks.Client.Test/JobApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/Microsoft.Azure.Databricks.Client.Test.csproj
  csharp/Microsoft.Azure.Databricks.Client/Microsoft.Azure.Databricks.Client.csproj
Labels: dependencies

#247 revert DataArray to string[][] in StatementExecutionResultChunk
  csharp/Microsoft.Azure.Databricks.Client.Test/StatementExecutionApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/StatementExecution.cs
Labels: bug
