Repository Azure/azure-databricks-client, pull requests merged in 2024-09, with the labels that each got.

#209 fix: Wrong request URI name for getting columns data lineage
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalog/LineageApiClient.cs
Labels: bug

#206 Add Databricks ML flow api endpoints
  csharp/Microsoft.Azure.Databricks.Client.Sample/SampleProgram .MachineLearning.cs
  csharp/Microsoft.Azure.Databricks.Client.Sample/SampleProgram.UnityCatalog.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/MachineLearning/ExperimentApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/MachineLearning/MachineLearningApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/UnityCatalog/ModelVersionApiClientTests.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/UnityCatalog/RegisteredModelsApiClientTests.cs
  csharp/Microsoft.Azure.Databricks.Client/ApiClient.cs
  csharp/Microsoft.Azure.Databricks.Client/DatabricksClient.cs
  csharp/Microsoft.Azure.Databricks.Client/MachineLearning/ExperimentApiClient.cs
  csharp/Microsoft.Azure.Databricks.Client/MachineLearning/IExperimentApi.cs
  csharp/Microsoft.Azure.Databricks.Client/MachineLearningClient.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/MachineLearning/Experiment/Run.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/RunResultState.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/UnityCatalog/ModelVersions.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/UnityCatalog/RegisteredModel.cs
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalog/Interfaces/IModelVersionApi.cs
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalog/Interfaces/IRegisteredModelsApi.cs
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalog/ModelVersionApiClient.cs
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalog/RegisteredModelApiClient.cs
  csharp/Microsoft.Azure.Databricks.Client/UnityCatalogClient.cs
Labels: enhancement

#214 Clean up build warnings
  csharp/Microsoft.Azure.Databricks.Client.Sample/SampleProgram.Jobs.cs
  csharp/Microsoft.Azure.Databricks.Client.Test/JobApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/Run.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/RunStatus.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/TerminationDetails.cs
Labels: bug

#220 Add GenerateDocumentationFile to make summaries show up in IDEs
  csharp/Microsoft.Azure.Databricks.Client/Microsoft.Azure.Databricks.Client.csproj
Labels: documentation

#222 fix documentation
  csharp/Microsoft.Azure.Databricks.Client/Microsoft.Azure.Databricks.Client.csproj
  csharp/Microsoft.Azure.Databricks.Client/Models/ClusterState.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/InstancePoolInfo.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/PipelineSpecification.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/StatementExecution.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/Tasks.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/Warehouse.cs
Labels: documentation

#223 Remove unused dependency
  csharp/Microsoft.Azure.Databricks.Client.Test/UnityCatalog/UnityCatalogApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/Microsoft.Azure.Databricks.Client.csproj
Labels: dependencies

#218 Bailey/add data security mode support
  csharp/Microsoft.Azure.Databricks.Client.Test/ClustersApiClientTest.cs
  csharp/Microsoft.Azure.Databricks.Client/Models/ClusterAttributes.cs
Labels: enhancement
